### ISSUE TITLE
Create VnV-test-Tng5 test (time instantiate the NS)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#67]
This test need to check the time it takes to instantiate the NS.
● We need a test which gets the time a new deployment takes.
● The curator must be able to collect the timestamps of instantiation events.

**Comment by DanielVilaFalcon** [comment]
It is necessary to modify the executor and the curator to be able to get  the time it takes to instantiate the NS. 
This issues will be done by @juanlucruz

**Comment by juanlucruz** [comment]
A new field has been added in https://github.com/sonata-nfv/tng-vnv-curator/pull/23, now the instantiation time is included as a string in test-result record

**Comment by juanlucruz** [comment]
New field is `service_instantiation_time` and it is in seconds.

Example:

`tng-cli -u http://pre-int-vnv-bcn.5gtango.eu result -g 61194a96-c20d-41bc-91c2-07ec1ee17b45`

```
created_at: '2019-08-01T10:26:41.025+00:00'
details:
- ffprobe: []
- parser: []
- cce: []
- cpe: []
- initiator: []
ended_at: '2019-08-01T10:26:40.974Z'
instance_uuid: 4a4a17f3-f3a4-4285-804c-656a325fadd2
package_id: e0645068-1abb-4058-a488-be1e4815d090
results:
- ffprobe:
  - '{


    }

    '
- parser:
  - '{"I-frames": 264, "lost-frames": 68}'
- cce:
  - ''
- cpe: []
- initiator: []
service_instantiation_time: '35.436341762542725'
service_uuid: e1ae4346-7094-4ba3-98fe-9e605a1c3ae8
started_at: '2019-08-01T10:25:39.943Z'
status: PASSED
test_instance_uuid: 32074e7d-ae6e-468c-a96d-0614f54ec43e
test_uuid: 8dba2e8e-0717-442e-b61f-3bff8bbedce9
updated_at: '2019-08-01T10:26:40.970+00:00'
uuid: 61194a96-c20d-41bc-91c2-07ec1ee17b45
```

**Comment by DanielVilaFalcon** [comment]
Finally, we have implement a container with the tng-cli tool installed on it. With it we can send request to the [pre-int-vnv-bcn.5gtango.eu](url), so that we can get the time needed to instantiate a Network Service.

The request sent to the VnV is: 

`tng-cli -e http://pre-int-vnv-bcn.5gtango.eu result -g 43b173d0-1f57-4f71-aa39-74e8e7860e63 >> /output/${PROBE}/$HOSTNAME/results.log`

The test UUID is introduced as an enviroment variable and it is the UUID of the test result of another completed test avaliable in the VnV platform 

In this way, we get the results in the VnV as it is shown in the following picture:
![image](https://user-images.githubusercontent.com/46524505/64265186-c3b14580-cf32-11e9-95f1-a90a8db1fed0.png)

**Comment by DanielVilaFalcon** [comment]
I have included the comparison between the obtained time and the requirements.

![image](https://user-images.githubusercontent.com/46524505/66311519-f1612400-e90e-11e9-8dc5-68d87b6a4cff.png)
