### ISSUE TITLE
Create VnV-test-Com-P2a test (rate of packets from WebRTC app to VNF)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#70]
This tests checks the rate of packets sent from the WebRTC application to
the VNF.
● Same considerations as VnV-test-Com-P1a

**Comment by antonroman** [comment]
As we can not use webrtc-internals we can use a tool to check the UDP traffic sent to VNF-MS.

**Comment by DanielVilaFalcon** [comment]
Due to we can not access to [chrome://webrtc-internals/](url) with the browser in head-less mode, we have used the command TSHARK to capture the traffic UDP and some statisticts of RTP stream. 

`sudo tshark -i any -q -f 'udp portrange 1-65000' -o rtp.heuristic_rtp:TRUE -q -z rtp,streams,stat -a duration:$capturingTime`

Additionally, we need to get UDT traffric sent or caming from a WebRTC application, so we run the head-less browser container to establish a WebRTC call.

From this UDP network traffic generated by the call, with the previous command we get max/mean jitter, max delta (max time between two consecutived received packets),  rate of packets sent and the rate of packet loss.

The next image shows the results obtained in the VnV platform:

![image](https://user-images.githubusercontent.com/46524505/63671182-24c47500-c7df-11e9-875f-2356f9c7f86b.png)
![image](https://user-images.githubusercontent.com/46524505/63671277-65bc8980-c7df-11e9-9e1c-34c6dade069a.png)

**Comment by DanielVilaFalcon** [comment]
Addictionally, I have also included the "IFTOP" monitoring CLI tool to get the throughput in Kb/s of the packets sent from the WebRTC application to the MS-VNF and vice versa.

![image](https://user-images.githubusercontent.com/46524505/66041375-00fcf900-e51a-11e9-8b85-16d715d13db8.png)
![image](https://user-images.githubusercontent.com/46524505/66041400-0fe3ab80-e51a-11e9-8d1d-014f56c4b3c9.png)
![image](https://user-images.githubusercontent.com/46524505/66041428-25f16c00-e51a-11e9-8006-650d77884196.png)

**Comment by DanielVilaFalcon** [comment]
Results update:
![image](https://user-images.githubusercontent.com/46524505/66733617-6927d500-ee60-11e9-9f20-deb7a12d356e.png)
![image](https://user-images.githubusercontent.com/46524505/66733634-78a71e00-ee60-11e9-9530-39a892db86a8.png)
![image](https://user-images.githubusercontent.com/46524505/66733682-9aa0a080-ee60-11e9-9b13-e557c0880e57.png)
![image](https://user-images.githubusercontent.com/46524505/66733703-a724f900-ee60-11e9-833f-f5b64f020ed1.png)
![image](https://user-images.githubusercontent.com/46524505/66733714-b015ca80-ee60-11e9-8e3f-92991a097705.png)
