### ISSUE TITLE
Create VnV-test-Com-P2b test (Packet loss from generic APP to VNF-MS)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#71]
This tests checks the packet loss of UDP traffic sent to the VNF-MS VNF from
a generic application.
● Same considerations as VnV-test-Com-P1b

**Comment by DanielVilaFalcon** [comment]
It is done. A container runs a ping and the output is printed in the VnV results, getting the sent packets and the percentage of lost packets lost.

**Comment by DanielVilaFalcon** [comment]
Due to we can not access to [chrome://webrtc-internals/](url) with the browser in head-less mode, we have used the command TSHARK to capture the traffic UDP and some statisticts of RTP stream. 

`sudo tshark -i any -q -f 'udp portrange 1-65000' -o rtp.heuristic_rtp:TRUE -q -z rtp,streams,stat -a duration:$capturingTime`

Additionally, we need to get UDT traffric sent or caming from a WebRTC application, so we run the head-less browser container to establish a WebRTC call.

From this UDP network traffic generated by the call, with the previous command we get max/mean jitter, max delta (max time between two consecutived received packets),  rate of packets sent and the rate of packet loss.

The next image shows the results obtained in the VnV platform:

![image](https://user-images.githubusercontent.com/46524505/63671182-24c47500-c7df-11e9-875f-2356f9c7f86b.png)
![image](https://user-images.githubusercontent.com/46524505/63671277-65bc8980-c7df-11e9-9e1c-34c6dade069a.png)

**Comment by DanielVilaFalcon** [comment]
I have included the comparison between the obtained result and the requirements.
![packetLoss](https://user-images.githubusercontent.com/46524505/66391831-76f7d900-e9ce-11e9-9997-52b9acdc577e.png)
