### ISSUE TITLE
Create VnV-test-Com-P4 test (registration per second managed by WAC-VNF)

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-communications-pilot#73]
This test checks a defined rate of registration per second can correctly
managed by the WAC-VNF
● The access should through the WAC-RP.

**Comment by DanielVilaFalcon** [comment]
@anapolg I have been able to increase the numbre of sippo server session from the V&V through "SAPI". The result shown in the portal is the result of the get request but it is not too descriptive. How could I probe that the WAC is still active after adding a defined number of sessions? (Maybe with a ping?)

![image](https://user-images.githubusercontent.com/46524505/66042934-1a07a900-e51e-11e9-996d-20af29468c7c.png)

**Comment by anapolg** [comment]
Maybe doing another request to GET the users after the request of posting the users?

**Comment by DanielVilaFalcon** [comment]
That is what I am actually doing, so I will modify the style of the result and this V&V test would be done.

**Comment by anapolg** [comment]
So.. the test is to create 10 users right? Then you should be able to GET the users and check that the returned result is equals 10. So yes, you should parse the result returned in that image and check if it is the same number as the number of users created in the probe (maybe a variable, maybe include it by hand...). This check must be done inside the test so that the result displayed in the Portal would be something like:
10 users were successfully created and managed?

**Comment by DanielVilaFalcon** [comment]
The test and the comparison with the requirement have been done properly.
![image](https://user-images.githubusercontent.com/46524505/66402164-b16c7080-e9e4-11e9-9389-12e44f72c877.png)
